version: '3.9'

services:
  database:
    container_name: mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: 
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    ports:
      - '3306:3306'
    volumes:
      - ./mysqldata:/var/lib/mysql
    restart: always
    networks:
      mysql-phpmyadmin:
        aliases:
          - mysql

  phpmyadmin:
    container_name: pma
    depends_on:
      - database
    image: phpmyadmin:latest
    ports:
      - '8081:80'
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    restart: always
    networks:
      mysql-phpmyadmin:
        aliases:
          - phpmyadmin

networks:
    mysql-phpmyadmin:
        name: mysql-phpmyadmin
        driver: bridge
        external: true
        # attachable: true

volumes:
  mysqldata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'