version: '3.9'

services:
  php:
    container_name: php
    build:
      context: ./php
    volumes:
      - ./logs:/var/log
      - ./projects:/var/www/html
    env_file:
      - ./.env
    networks:
      mysql-phpmyadmin: {}

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - '8080:80'
      - '443:443'
    volumes:
      - ./projects:/var/www/html
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/ssl/certs
      - ./nginx/certs:/etc/ssl/private
      - ./nginx/auth:/etc/nginx/auth
      - ./logs:/var/log/nginx
    depends_on:
      - php
    networks:
      mysql-phpmyadmin: {}

networks:
  mysql-phpmyadmin:
    external: true