version: '3.9'

services:
  php:
    # image: php8.2-fpm-mongo
    container_name: php
    build:
      context: ./php
    volumes:
      - ./app:/var/www/html
      - ./logs:/var/log
    env_file:
      - ./.env
    # environment:
    #   DB_USERNAME: root
    #   DB_PASSWORD: secret
    #   DB_HOST: mongodb # matches the service with mongodb
    networks:
      mysql-phpmyadmin: {}
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx
    depends_on:
      - php
    networks:
      mysql-phpmyadmin: {}

networks:
  mysql-phpmyadmin:
    external: true